identifier: k5yc057cucs1x0xa
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: rustBlog
homeFolder: /home/mate/WebstormProjects/rustBlog
distFolder: dist/rust-blog
outDir: /home/mate/WebstormProjects/rustBlog/dist/static
handle404: ''
allowErrorCollect: true
